apiVersion: v1
kind: Namespace
metadata:
  name: crozz-coin
  labels:
    name: crozz-coin
    environment: production
    app.kubernetes.io/name: crozz-coin
    app.kubernetes.io/part-of: crozz-ecosystem
